# Generated by Django 5.1.15 on 2026-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, '😞'), (2, '🙁'), (3, '😐'), (4, '🙂'), (5, '😄')], default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
